---
apiVersion: v1
kind: ConfigMapdAdsasS
metadata:
  name: nginx2-index
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>NGINX 2</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        h1 { color: #007bff; }
      </style>
    </head>
    <body>
      <h1>This is nginx 2</h1>
      <p>Your fake production app instance is up and running!</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx2-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-svc
spec:
  type: NodePort
  selector:
    app: nginx-2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32062
